[package]
name = "seal-unseal-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
hpke = { version = "0.11", features = ["serde_impls"] }
rand = "0.8"
ed25519-dalek = { version = "2", features = [ "rand_core", "pkcs8" ] }
